/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author hp 14
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtPersona1 = new javax.swing.JTextField();
        TxtPersona2 = new javax.swing.JTextField();
        TxtPersona3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtInversion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtPorcentaje1 = new javax.swing.JTextField();
        TxtPorcentaje2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtPorcentaje3 = new javax.swing.JTextField();
        TxtNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel1.setText("Porcentajes De Inversiones ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 230, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Ingrese Su Inversión ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, -1, 30));

        TxtPersona1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPersona1KeyTyped(evt);
            }
        });
        jPanel1.add(TxtPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        TxtPersona2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPersona2KeyTyped(evt);
            }
        });
        jPanel1.add(TxtPersona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, -1));

        TxtPersona3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPersona3KeyTyped(evt);
            }
        });
        jPanel1.add(TxtPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Persona 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Persona 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Persona 3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        cmdCalcular.setBackground(new java.awt.Color(0, 0, 0));
        cmdCalcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdCalcular.setForeground(new java.awt.Color(255, 255, 255));
        cmdCalcular.setText("OK");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Inversion Total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel1.add(TxtInversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText(" Porcentaje de Persona1 :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel1.add(TxtPorcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, -1));
        jPanel1.add(TxtPorcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 280, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Porcentaje de Persona 2:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Porcentaje de Persona 3 :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        jPanel1.add(TxtPorcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 320, 180, -1));

        TxtNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNuevo.setText("Nueva Consulta");
        TxtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        String inversion,porcen1,porcen2,porcen3;
        double i1,i2,i3;
        
        if (TxtPersona1.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite La primera inversion ","error", JOptionPane.ERROR_MESSAGE);
         TxtPersona1.requestFocusInWindow();
        }else if(TxtPersona2.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite La segunda inversion ","error", JOptionPane.ERROR_MESSAGE);
         TxtPersona2.requestFocusInWindow();
        }else if(TxtPersona3.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite La tercera inversion ","error", JOptionPane.ERROR_MESSAGE);
         TxtPersona3.requestFocusInWindow();}
        else{
        i1=Double.parseDouble(TxtPersona1.getText());
        i2=Double.parseDouble(TxtPersona2.getText());
        i3=Double.parseDouble(TxtPersona3.getText());
        double inver=i1+i2+i3;
        inversion=String.valueOf(inver);
     TxtInversion.setText(inversion);
     
     
     double porcentaje1=(i1*100)/inver;
     double porcentaje2=(i2*100)/inver;
     double porcentaje3=(i3*100)/inver;
     
     porcen1=String.valueOf(porcentaje1);
     TxtPorcentaje1.setText(porcen1+"%");
     
     porcen2=String.valueOf(porcentaje2);
     TxtPorcentaje2.setText(porcen2+"%");
     
     porcen3=String.valueOf(porcentaje3);
     TxtPorcentaje3.setText(porcen3+"%");
        
        
        }    
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void TxtPersona1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPersona1KeyTyped
        char c=evt.getKeyChar(); 
            
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
              evt.consume();}
    }//GEN-LAST:event_TxtPersona1KeyTyped

    private void TxtPersona2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPersona2KeyTyped
        char c=evt.getKeyChar(); 
         
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
              evt.consume();}
    }//GEN-LAST:event_TxtPersona2KeyTyped

    private void TxtPersona3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPersona3KeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
              evt.consume();}
    }//GEN-LAST:event_TxtPersona3KeyTyped

    private void TxtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNuevoActionPerformed
        TxtPersona1.setText("");
     TxtPersona2.setText("");
     TxtPersona3.setText("");
     TxtPorcentaje1.setText("");
     TxtPorcentaje2.setText("");
     TxtPorcentaje3.setText("");
     TxtInversion.setText("");
     
     TxtPersona1.requestFocusInWindow();
    }//GEN-LAST:event_TxtNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtInversion;
    private javax.swing.JButton TxtNuevo;
    private javax.swing.JTextField TxtPersona1;
    private javax.swing.JTextField TxtPersona2;
    private javax.swing.JTextField TxtPersona3;
    private javax.swing.JTextField TxtPorcentaje1;
    private javax.swing.JTextField TxtPorcentaje2;
    private javax.swing.JTextField TxtPorcentaje3;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
